(()=>{'use strict';
const D=window.ROLL_DATA;if(!D)throw Error('ROLL_DATA missing');
const {RS,RC,SH,DUP,TITLE_INCOME_BONUS,COLOR_LUCK,FONT_TIME_REDUCTION,titles,colors,fonts}=D;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const STORE='roll_titles_v5',COST=250,BASE_INCOME=300,BASE_INTERVAL=60000,START=1000,pools={title:titles,color:colors,font:fonts};
const get=(t,id)=>pools[t]?.find(x=>x.id===id),tier=x=>Math.max(0,RS.indexOf(x?.rarity));
const fresh=()=>({inventory:{title:{},color:{},font:{}},equipped:{},rolls:0,history:[],coins:START,lastIncomeAt:Date.now()});
let s;try{s=JSON.parse(localStorage.getItem(STORE))||fresh()}catch{s=fresh()}
s.inventory||={title:{},color:{},font:{}};for(const t of ['title','color','font'])s.inventory[t]||={};s.equipped||={};s.history||=[];s.rolls=+s.rolls||0;s.coins=Number.isFinite(+s.coins)?+s.coins:START;s.lastIncomeAt=+s.lastIncomeAt||Date.now();
const defs={title:titles.find(x=>x.name==='Player')||titles[0],color:colors.find(x=>x.name==='White')||colors[0],font:fonts.find(x=>x.name==='Space Grotesk')||fonts[0]};
for(const t of ['title','color','font'])if(!get(t,s.equipped[t])){s.equipped[t]=defs[t].id;s.inventory[t][defs[t].id]=Math.max(1,s.inventory[t][defs[t].id]||0)}
const save=()=>localStorage.setItem(STORE,JSON.stringify(s));
let type='title',rolling=false,auto=false,filter='all',rollState=null;
const equippedItem=t=>get(t,s.equipped[t])||defs[t],titlePayout=()=>BASE_INCOME+TITLE_INCOME_BONUS[tier(equippedItem('title'))],colorLuck=()=>COLOR_LUCK[tier(equippedItem('color'))],payoutInterval=()=>BASE_INTERVAL-FONT_TIME_REDUCTION[tier(equippedItem('font'))];
function rarityShares(t){const luck=colorLuck(),base=SH[t],w=base.map((v,i)=>v*(1+luck*(i/6))),sum=w.reduce((a,b)=>a+b,0);return w.map(v=>v/sum*100)}
function pick(t){const sh=rarityShares(t);let n=Math.random()*100,a=0,r=RS[0];for(let i=0;i<RS.length;i++){a+=sh[i];if(n<=a){r=RS[i];break}}const p=pools[t].filter(x=>x.rarity===r),sum=p.reduce((v,x)=>v+x.weight,0);let q=Math.random()*sum;for(const x of p){q-=x.weight;if(q<=0)return x}return p[p.length-1]}
function exact(x){const a=pools[x.type].filter(y=>y.rarity===x.rarity),sum=a.reduce((v,y)=>v+y.weight,0),share=rarityShares(x.type)[tier(x)]/100;return share*x.weight/sum}
const pct=x=>{const p=exact(x)*100;return p>=1?p.toFixed(2)+'%':p>=.1?p.toFixed(3)+'%':p.toFixed(4)+'%'},one=x=>Math.max(1,Math.round(1/exact(x)));
function clear(e){if(!e)return;[...e.classList].filter(c=>c==='text-gradient'||c.startsWith('fx-')).forEach(c=>e.classList.remove(c));['color','backgroundImage','backgroundSize','fontFamily','fontWeight','letterSpacing','fontStyle','textTransform','filter'].forEach(p=>e.style[p]='')}
function applyFont(e,x){if(!e||!x)return;e.style.fontFamily=`"${x.family}",sans-serif`;if(x.style)for(const z of x.style.split(';').filter(Boolean)){const i=z.indexOf(':');if(i>0)e.style.setProperty(z.slice(0,i),z.slice(i+1))}}
function paint(e,x,text=x.name){if(!e||!x)return;clear(e);e.textContent=text;if(x.type==='color'){(x.classes||'').split(/\s+/).filter(Boolean).forEach(c=>e.classList.add(c));if(x.solid)e.style.color=x.solid;if(x.gradient){e.style.backgroundImage=x.gradient;e.style.backgroundSize='300% 100%';e.classList.add('text-gradient')}}else if(x.type==='font')applyFont(e,x)}
function paintRoll(e,x,text=x.name){paint(e,x,text);if(x.type!=='color')e.style.color=RC[x.rarity]||'#fff'}
function itemBonus(x){const i=tier(x);if(x.type==='title')return i?`PAYOUT +${TITLE_INCOME_BONUS[i].toLocaleString()} ◈`:'BASE PAYOUT';if(x.type==='color')return i?`LUCK +${Math.round(COLOR_LUCK[i]*100)}%`:'BASE LUCK';const sec=FONT_TIME_REDUCTION[i]/1000;return sec?`PAYOUT TIMER -${sec}s`:'BASE TIMER'}
function toast(m){const e=$('#toast');if(!e)return;e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1700)}
let audioCtx=null;
function audio(){try{if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}catch{return null}}
function tone(freq=440,dur=.06,vol=.025,wave='sine',delay=0,slide=0){const a=audio();if(!a)return;const o=a.createOscillator(),g=a.createGain(),now=a.currentTime+delay;o.type=wave;o.frequency.setValueAtTime(freq,now);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(30,freq+slide),now+dur);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(Math.max(.0002,vol),now+.008);g.gain.exponentialRampToValueAtTime(.0001,now+dur);o.connect(g);g.connect(a.destination);o.start(now);o.stop(now+dur+.02)}
function noiseBurst(dur=.09,vol=.012){const a=audio();if(!a)return;const len=Math.max(1,Math.floor(a.sampleRate*dur)),buf=a.createBuffer(1,len,a.sampleRate),data=buf.getChannelData(0);for(let i=0;i<len;i++)data[i]=(Math.random()*2-1)*(1-i/len);const src=a.createBufferSource(),g=a.createGain(),f=a.createBiquadFilter();f.type='highpass';f.frequency.value=900;g.gain.value=vol;src.buffer=buf;src.connect(f);f.connect(g);g.connect(a.destination);src.start()}
const sfxStart=()=>{tone(150,.12,.028,'sawtooth',0,120);noiseBurst(.12,.009)},sfxTick=p=>tone(410+(p||0)*140,.028,.017,'square',0,35),sfxDuplicate=()=>{tone(220,.07,.022,'square');tone(330,.09,.018,'triangle',.06,45)};
function sfxReveal(x){const i=tier(x),root=320+i*42;tone(root,.18,.035,'sine',0,120);tone(root*1.25,.24,.028,'sine',.075,80);tone(root*1.5,.32,.024,'triangle',.15,100);if(i>=4)tone(root*2,.44,.017,'sine',.22,180);if(i>=6){tone(root*2.5,.62,.014,'sine',.32,220);noiseBurst(.16,.012)}}
function stats(){const n=t=>Object.keys(s.inventory[t]).filter(id=>get(t,id)).length,a=n('title'),b=n('color'),c=n('font'),u=a+b+c;[['#rollCount',s.rolls.toLocaleString()],['#uniqueCount',u],['#invCount',u],['#invAllCount',u],['#invTitleCount',a],['#invColorCount',b],['#invFontCount',c],['#colTitles',`${a} / ${titles.length}`],['#colColors',`${b} / ${colors.length}`],['#colFonts',`${c} / ${fonts.length}`]].forEach(([q,v])=>{if($(q))$(q).textContent=v});if($('#barTitles'))$('#barTitles').style.width=a/titles.length*100+'%';if($('#barColors'))$('#barColors').style.width=b/colors.length*100+'%';if($('#barFonts'))$('#barFonts').style.width=c/fonts.length*100+'%'}
function buttons(){const no=rolling||auto||s.coins<COST;if($('#rollBtn'))$('#rollBtn').disabled=no;if($('#autoBtn'))$('#autoBtn').disabled=no}
function wallet(){const payout=titlePayout(),interval=payoutInterval(),timer=Math.max(0,Math.ceil((s.lastIncomeAt+interval-Date.now())/1000));if($('#coinBalance'))$('#coinBalance').textContent=Math.floor(s.coins).toLocaleString();const old=$('#incomeTimer');if(old){const line=old.parentElement;if(line)line.innerHTML=`+${payout.toLocaleString()} / ${interval/1000}s · IN <strong id="incomeTimer">${timer}s</strong>`}const w=$('.wallet');if(w)w.title=`Title payout: ${payout.toLocaleString()} every ${interval/1000}s · Color luck: +${Math.round(colorLuck()*100)}%`;buttons()}
function income(show=false){const now=Date.now(),interval=payoutInterval(),m=Math.floor(Math.max(0,now-s.lastIncomeAt)/interval);if(m){const gain=m*titlePayout();s.coins+=gain;s.lastIncomeAt+=m*interval;save();if(show)toast(`+${gain.toLocaleString()} coins · title payout`)}wallet()}
function equipped(){const t=equippedItem('title'),c=equippedItem('color'),f=equippedItem('font'),e=$('#equippedTitle');paint(e,c,t.name);applyFont(e,f);$('#eqTitleName').textContent=t.name;$('#eqColorName').textContent=c.name.toUpperCase();$('#eqFontName').textContent=f.name.toUpperCase();applyFont($('#eqFontName'),f);wallet()}
function view(v){const e=$('#'+v+'View');if(!e)return;$$('.view').forEach(x=>x.classList.remove('active'));e.classList.add('active');$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='inventory')inventory();if(v==='collection')catalog()}
function select(t){if(!pools[t]||rolling)return;type=t;$$('.case-card').forEach(x=>x.classList.toggle('selected',x.dataset.case===t));$('#machineEyebrow').textContent=t.toUpperCase()+' CASE';$('#machineTitle').textContent='ROLL A '+t.toUpperCase();idle();odds()}
function row(x,c=false){const d=document.createElement('div');d.className='reel-item'+(c?' centerish':'');d.innerHTML=`<span class="rarity" style="color:${RC[x.rarity]}">${x.rarity.toUpperCase()}</span><span class="name"></span><span class="chance">${pct(x)}</span>`;paintRoll(d.querySelector('.name'),x);return d}
function focusRow(tr,index){[...tr.children].forEach((e,i)=>e.classList.toggle('roll-focus',i===index))}
function idle(){const tr=$('#reelTrack');if(!tr)return;tr.innerHTML='';for(let i=0;i<7;i++)tr.appendChild(row(pick(type),i===3));tr.style.transition='none';tr.style.transform='translateY(-266px)';$('#resultRarity').textContent='READY';$('#resultRarity').style.color='#6e788d';clear($('#resultName'));$('#resultName').textContent='Press roll to start';$('#resultOdds').textContent='—';$('#skipRoll')?.classList.remove('show')}
function add(x){const n=s.inventory[x.type][x.id]||0,dup=n>0,refund=dup?DUP[tier(x)]:0;s.inventory[x.type][x.id]=n+1;s.rolls++;s.coins+=refund;s.history.unshift({type:x.type,id:x.id,dup,refund});s.history=s.history.slice(0,24);save();stats();wallet();history();return{dup,refund}}
function animateReel(tr,n,duration){return new Promise(resolve=>{const target=-((n-1)*76)-38,started=performance.now();let last=-1;function frame(now){if(!rollState){resolve();return}let t=Math.min(1,(now-started)/duration);if(rollState.skip)t=1;const eased=1-Math.pow(1-t,2.7),y=target*eased;tr.style.transform=`translateY(${y}px)`;const idx=Math.max(0,Math.min(n-1,Math.round((-y-38)/76)));if(idx!==last){last=idx;focusRow(tr,idx);if(t>.035)sfxTick(idx/Math.max(1,n-1))}if(t<1)rollState.raf=requestAnimationFrame(frame);else resolve()}rollState.raf=requestAnimationFrame(frame)})}
function revealVfx(x){const shell=$('#reelShell');if(!shell)return;const layer=shell.querySelector('.roll-vfx-layer');if(!layer)return;layer.innerHTML='';const color=x.type==='color'?(x.solid||RC[x.rarity]):RC[x.rarity],flash=document.createElement('div');flash.className='reveal-flash';flash.style.setProperty('--rarity',color);layer.appendChild(flash);const ring=document.createElement('div');ring.className='reveal-ring';ring.style.setProperty('--rarity',color);layer.appendChild(ring);const count=16+tier(x)*3;for(let i=0;i<count;i++){const p=document.createElement('i'),a=(Math.PI*2/count)*i+(Math.random()-.5)*.18,dist=80+Math.random()*(65+tier(x)*9);p.className='reveal-particle';p.style.setProperty('--x',`${Math.cos(a)*dist}px`);p.style.setProperty('--y',`${Math.sin(a)*dist*.52}px`);p.style.setProperty('--rarity',i%4===0?'#fff':color);p.style.animationDelay=(Math.random()*.08)+'s';layer.appendChild(p)}const strip=$('#resultStrip');strip?.classList.remove('result-pop');void strip?.offsetWidth;strip?.classList.add('result-pop');document.body.classList.add('reveal-kick');setTimeout(()=>{layer.innerHTML='';strip?.classList.remove('result-pop');document.body.classList.remove('reveal-kick')},1100+tier(x)*70)}
async function roll(q=false){if(rolling)return null;income();if(s.coins<COST){toast('Not enough coins');return null}s.coins-=COST;rolling=true;save();wallet();buttons();audio();sfxStart();const x=pick(type),tr=$('#reelTrack'),n=q?18:42;tr.innerHTML='';for(let i=0;i<n-1;i++)tr.appendChild(row(pick(type)));tr.appendChild(row(x));tr.style.transition='none';tr.style.transform='translateY(0)';$('#resultRarity').textContent='ROLLING';$('#resultRarity').style.color='#fff';clear($('#resultName'));$('#resultName').textContent='Scanning drops…';$('#resultOdds').textContent='—';rollState={skip:false,raf:0};const skip=$('#skipRoll');if(skip){skip.disabled=false;skip.textContent='SKIP ANIMATION';skip.classList.add('show')}await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));await animateReel(tr,n,q?2200:5200);if(rollState?.raf)cancelAnimationFrame(rollState.raf);rollState=null;if(skip)skip.classList.remove('show');focusRow(tr,n-1);tr.lastElementChild?.classList.add('winner-glow');const d=add(x);$('#resultRarity').textContent=x.rarity.toUpperCase();$('#resultRarity').style.color=RC[x.rarity];paintRoll($('#resultName'),x);$('#resultOdds').textContent=d.dup?`DUPLICATE +${d.refund} ◈`:`${pct(x)} · 1/${one(x).toLocaleString()}`;revealVfx(x);sfxReveal(x);if(d.dup)setTimeout(sfxDuplicate,180);setTimeout(()=>tr.lastElementChild?.classList.remove('winner-glow'),1450);rolling=false;buttons();return x}
function skipAnimation(){if(!rolling||!rollState)return;rollState.skip=true;const b=$('#skipRoll');if(b){b.textContent='SKIPPING…';b.disabled=true}}
function history(){const g=$('#historyList');if(!g)return;g.innerHTML='';if(!s.history.length){g.innerHTML='<div class="empty-mini">No rolls yet.</div>';return}s.history.slice(0,6).forEach(h=>{const x=get(h.type,h.id);if(!x)return;const d=document.createElement('div');d.className='history-item';d.innerHTML=`<small style="color:${RC[x.rarity]}">${x.rarity.toUpperCase()} · ${x.type.toUpperCase()}</small><b></b><em>${pct(x)}</em>${h.dup?`<span class="dup-refund">DUP +${h.refund} ◈</span>`:''}`;paintRoll(d.querySelector('b'),x);g.appendChild(d)})}
function card(x,inv=false,qty=0){const c=document.createElement('div'),owned=!!s.inventory[x.type][x.id];c.className=(inv?'inv-card':'col-card')+(inv?'':owned?' owned':' locked');c.innerHTML=`<div class="item-top"><span class="item-type">${x.type.toUpperCase()}</span><span class="item-rarity" style="color:${RC[x.rarity]}">${x.rarity.toUpperCase()}</span></div><div class="item-preview"></div><div class="item-name"></div><div class="item-sub">${pct(x)} · ~1 in ${one(x).toLocaleString()}</div><div class="item-bonus">${itemBonus(x)}</div>${inv?`<div class="item-actions"><button class="equip-btn">${s.equipped[x.type]===x.id?'EQUIPPED':'EQUIP'}</button><span class="qty">×${qty}</span></div>`:'<span class="owned-dot"></span>'}`;paint(c.querySelector('.item-preview'),x);c.querySelector('.item-name').textContent=x.name;if(x.type==='font')applyFont(c.querySelector('.item-name'),x);if(inv)c.querySelector('button').onclick=()=>{income(false);s.equipped[x.type]=x.id;s.lastIncomeAt=Date.now();save();equipped();inventory();odds();toast(`${x.name} equipped · ${itemBonus(x)}`)};return c}
function inventory(){const g=$('#inventoryGrid');if(!g)return;const q=($('#invSearch')?.value||'').toLowerCase();let a=[];for(const t of ['title','color','font'])for(const[id,qty]of Object.entries(s.inventory[t])){const x=get(t,id);if(x)a.push({...x,qty})}a=a.filter(x=>(filter==='all'||x.type===filter)&&(!q||x.name.toLowerCase().includes(q)));g.innerHTML='';a.sort((x,y)=>tier(y)-tier(x)||x.name.localeCompare(y.name)).forEach(x=>g.appendChild(card(x,true,x.qty)));if(!a.length)g.innerHTML='<div class="empty-mini">Nothing here yet.</div>'}
function catalog(){const g=$('#collectionGrid');if(!g)return;const t=$('#collectionType')?.value||'all',r=$('#collectionRarity')?.value||'all',q=($('#collectionSearch')?.value||'').toLowerCase();let a=t==='all'?[...titles,...colors,...fonts]:[...pools[t]];a=a.filter(x=>(r==='all'||x.rarity===r)&&(!q||x.name.toLowerCase().includes(q)));g.innerHTML='';a.sort((x,y)=>tier(x)-tier(y)||x.name.localeCompare(y.name)).forEach(x=>g.appendChild(card(x)))}
function odds(){const g=$('#oddsRarities');if(!g)return;g.innerHTML='';$('#oddsTitle').textContent=type.toUpperCase()+' CASE ODDS';const sh=rarityShares(type);RS.forEach((r,i)=>{const d=document.createElement('div');d.className='odds-row';d.innerHTML=`<span style="color:${RC[r]}">${r.toUpperCase()}</span><b>${sh[i].toFixed(sh[i]<1?2:1)}%</b>`;g.appendChild(d)});const d=$('#duplicateRewards');if(d){d.innerHTML='';RS.forEach((r,i)=>d.insertAdjacentHTML('beforeend',`<div class="duplicate-row"><span style="color:${RC[r]}">${r.toUpperCase()}</span><b>+${DUP[i]} ◈</b></div>`))}}
function adminItems(){const t=$('#adminGrantType')?.value||'coins';$('#adminAmountWrap')?.classList.toggle('hidden',t!=='coins');$('#adminItemWrap')?.classList.toggle('hidden',!pools[t]);const e=$('#adminItem');if(e&&pools[t]){e.innerHTML='';[...pools[t]].sort((a,b)=>tier(b)-tier(a)||a.name.localeCompare(b.name)).forEach(x=>e.insertAdjacentHTML('beforeend',`<option value="${x.id}">${x.rarity.toUpperCase()} — ${x.name}</option>`))}}
async function grant(){const st=$('#adminStatus');try{st.textContent='Checking…';const res=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:$('#adminCode').value})}),j=await res.json().catch(()=>({}));if(!res.ok||!j.ok)throw Error(j.error||'Invalid code');const t=$('#adminGrantType').value;if(t==='coins'){const n=Math.floor(+$('#adminAmount').value);if(!(n>0&&n<=1e9))throw Error('Invalid amount');s.coins+=n}else if(t==='all'){for(const k of ['title','color','font'])for(const x of pools[k])s.inventory[k][x.id]=Math.max(1,s.inventory[k][x.id]||0)}else{const x=get(t,$('#adminItem').value);if(!x)throw Error('Item not found');s.inventory[t][x.id]=Math.max(1,s.inventory[t][x.id]||0)}save();stats();wallet();inventory();catalog();st.className='admin-status good';st.textContent='Grant applied';toast('Admin grant applied')}catch(e){st.className='admin-status bad';st.textContent=e.message}}
function particles(){const cv=$('#particles'),ctx=cv?.getContext('2d');if(!cv||!ctx)return;let W=0,H=0,D=1,pts=[];function resize(){D=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;cv.width=W*D;cv.height=H*D;ctx.setTransform(D,0,0,D,0,0);pts=Array.from({length:Math.min(80,Math.floor(W*H/17000))},()=>({x:Math.random()*W,y:Math.random()*H,r:Math.random()*1.2+.25,v:Math.random()*.12+.025,a:Math.random()*.35+.07}))}function frame(){ctx.clearRect(0,0,W,H);for(const p of pts){p.y-=p.v;if(p.y<-4){p.y=H+4;p.x=Math.random()*W}ctx.globalAlpha=p.a;ctx.fillStyle='#bfefff';ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}requestAnimationFrame(frame)}addEventListener('resize',resize);resize();frame()}
function ensureExtras(){for(const href of ['rollfx.css','fonts-extra.css'])if(!document.querySelector(`link[href="${href}"]`)){const l=document.createElement('link');l.rel='stylesheet';l.href=href;document.head.appendChild(l)}const shell=$('#reelShell');if(shell&&!shell.querySelector('.roll-vfx-layer')){const layer=document.createElement('div');layer.className='roll-vfx-layer';shell.appendChild(layer)}if(shell&&!$('#skipRoll')){const b=document.createElement('button');b.id='skipRoll';b.className='skip-roll';b.type='button';b.textContent='SKIP ANIMATION';b.onclick=skipAnimation;shell.appendChild(b)}}
function boot(){ensureExtras();$$('.tab').forEach(b=>b.onclick=()=>view(b.dataset.view));$$('.case-card').forEach(b=>b.onclick=()=>select(b.dataset.case));$$('.load-chip').forEach(b=>b.onclick=()=>{filter=b.dataset.go;view('inventory');$$('#invTabs button').forEach(x=>x.classList.toggle('active',x.dataset.filter===filter));inventory()});$$('#invTabs button').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$('#invTabs button').forEach(x=>x.classList.toggle('active',x===b));inventory()});$('#invSearch').oninput=inventory;$('#collectionType').onchange=catalog;$('#collectionRarity').onchange=catalog;$('#collectionSearch').oninput=catalog;$('#rollBtn').onclick=()=>roll();$('#autoBtn').onclick=async()=>{if(auto||rolling)return;auto=true;buttons();let n=0;for(let i=0;i<10;i++){const x=await roll(true);if(!x)break;n++;await new Promise(r=>setTimeout(r,100))}auto=false;buttons();toast(`Auto finished: ${n}`)};$('#clearHistory').onclick=()=>{s.history=[];save();history()};$('#oddsBtn').onclick=()=>{odds();$('#oddsDialog').showModal()};$('#closeOdds').onclick=()=>$('#oddsDialog').close();$('#adminOpen').onclick=()=>{adminItems();$('#adminStatus').textContent='';$('#adminDialog').showModal()};$('#adminClose').onclick=()=>$('#adminDialog').close();$('#adminGrantType').onchange=adminItems;$('#adminGrant').onclick=grant;const l=$('#rarityLegend');if(l){l.innerHTML='';RS.forEach(r=>l.insertAdjacentHTML('beforeend',`<span class="rarity-pill"><b style="color:${RC[r]}">●</b>${r}</span>`))}const rr=$('#collectionRarity');if(rr.options.length===1)RS.forEach(r=>rr.insertAdjacentHTML('beforeend',`<option value="${r}">${r}</option>`));$('#titlePoolCount').textContent=titles.length;$('#colorPoolCount').textContent=colors.length;$('#fontPoolCount').textContent=fonts.length;const ct=$('#collectionType');ct.querySelector('[value="title"]').textContent=`Titles (${titles.length})`;ct.querySelector('[value="color"]').textContent=`Colors (${colors.length})`;ct.querySelector('[value="font"]').textContent=`Fonts (${fonts.length})`;income();setInterval(()=>income(true),1000);idle();equipped();stats();wallet();history();odds();adminItems();particles();save()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();