(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const STORAGE='roll_titles_v1';
const RARITY_ORDER=['Common','Uncommon','Rare','Epic','Legendary','Mythic','Secret'];
const RARITY={Common:{c:'#aeb7c4',soft:'rgba(174,183,196,.12)'},Uncommon:{c:'#62d894',soft:'rgba(98,216,148,.12)'},Rare:{c:'#58a9ff',soft:'rgba(88,169,255,.13)'},Epic:{c:'#aa72ff',soft:'rgba(170,114,255,.14)'},Legendary:{c:'#ffb34e',soft:'rgba(255,179,78,.14)'},Mythic:{c:'#ff5c9e',soft:'rgba(255,92,158,.14)'},Secret:{c:'#effdff',soft:'rgba(160,245,255,.18)'}};
const SHARES={title:{Common:45,Uncommon:25,Rare:14,Epic:8,Legendary:4.5,Mythic:2.5,Secret:1},color:{Common:48,Uncommon:25,Rare:13,Epic:7,Legendary:4,Mythic:2,Secret:1},font:{Common:40,Uncommon:25,Rare:15,Epic:9,Legendary:6,Mythic:3.5,Secret:1.5}};
const TITLE_NAMES={
Common:['Rookie','Player','Wanderer','Scout','Runner','Chill','Regular','New Face','Day One','Night Owl','Quick Hands','Low Key','No Rush','Solo Queue','Casual','Warmup','On Time','Good Luck','Just Here','The Backup','Side Quest','Locked In','Coffee Break','AFK-ish','Late Join','Fresh Start','One More','Main Menu','Safe Pick','Clean Slate','No Pressure','Easy Mode','Small Win','First Try','Next Up','Silent Type','The Usual','Plain Sight','Half Awake','Checkpoint','Good Enough','Lucky One','The Local','Second Wind','Steady','No Drama','Passing By','Starter Pack','Just Vibing','On Standby'],
Uncommon:['Hot Streak','Lone Wolf','No Signal','Clutch-ish','Fast Learner','Cold Hands','Good Timing','Night Shift','Early Access','Second Chance','One Tap','Full Focus','No Context','Clean Run','Side Character','Plot Armor','Unbothered','Peak Hours','Quiet Storm','Wild Card','Lucky Break','Close Call','Final Form?','Top Shelf','High Ground','No Sleep','After Hours','Main Character','Quick Reset','Zero Panic','Ghosted','Last Online','Low Battery','Rare Sight','Fresh Spawn','Off Script','Good Aim','Fast Lane','Sharp Mind','Late Night','Hidden Gem'],
Rare:['Apex Hunter','Neon Ghost','Final Round','Out of Bounds','Zero Hour','Silent Winner','Blue Flame','Dead Center','No Witness','Overclocked','Cold Blooded','Midnight Run','Perfect Timing','Unseen','Top Frag','Afterimage','Redline','Last Call','Hard Reset','Untouchable','No Recoil','Ghost Signal','Prime Time','Dark Horse','Ace Up','Skyline','Critical Hit','One Percent','Night Rider','Endgame','No Footsteps','Crosshair King','Half Past Midnight','Static Rush','Final Push'],
Epic:['Void Walker','Neon Phantom','Reality Check','Final Boss','Unchained','Blackout','Phase Shift','Dead Serious','Limit Break','Perfect Chaos','No Mercy','Lost Frequency','After Midnight','Cold Eclipse','Zero Gravity','Unreal','Last Light','Broken Halo','Static Heart','Purple Haze','Unwritten','False Prophet','Ghost Protocol','Overdrive','Neon Saint','Dead Channel','Glass Cannon','Phantom Mode'],
Legendary:['THE CHOSEN ONE','LAST SURVIVOR','KING OF NOTHING','FINAL WARNING','BORN LUCKY','NO SECOND PLACE','THE UNTOUCHABLE','END OF LINE','LIVING LEGEND','LAST ONE STANDING','CROWNLESS KING','THE ORIGINAL','PERFECT STORM','ONE ABOVE ALL','FINAL ANSWER','NO TURNING BACK','ETERNAL WINNER','THE MAIN EVENT','LAST WORD','NO CONTEST'],
Mythic:['REALITY BREAKER','BEYOND LIMITS','THE UNFORGOTTEN','NOT FROM HERE','WORLD ENDER','TIMELESS','VOIDBORN','THE IMPOSSIBLE','ABSOLUTE ZERO','FATE DENIED','ETERNAL ECHO','THE ANOMALY','UNKNOWN ENTITY','OUTSIDE REALITY'],
Secret:['NULL','404 : NOT FOUND','BEYOND','UNDEFINED','[ REDACTED ]','GODMODE','???','THE LAST TITLE','DO NOT ROLL','∞']};
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
const titles=[];Object.entries(TITLE_NAMES).forEach(([rarity,names])=>names.forEach(name=>titles.push({id:'t_'+hash(name).toString(36),type:'title',name,rarity,weight:.72+(hash(name)%57)/100})));
const colors=[
{id:'white',name:'White',rarity:'Common',solid:'#f4f7fb'},{id:'silver',name:'Silver',rarity:'Common',solid:'#b8c0cc'},{id:'slate',name:'Slate',rarity:'Common',solid:'#7f8a9d'},{id:'charcoal',name:'Charcoal',rarity:'Common',solid:'#555d6b'},{id:'red',name:'Red',rarity:'Common',solid:'#ff5d67'},{id:'blue',name:'Blue',rarity:'Common',solid:'#5d9dff'},{id:'green',name:'Green',rarity:'Common',solid:'#61d98c'},{id:'orange',name:'Orange',rarity:'Common',solid:'#ff9b54'},
{id:'purple',name:'Purple',rarity:'Uncommon',solid:'#a375ff'},{id:'pink',name:'Pink',rarity:'Uncommon',solid:'#ff6fab'},{id:'cyan',name:'Cyan',rarity:'Uncommon',solid:'#66edff'},{id:'lime',name:'Lime',rarity:'Uncommon',solid:'#c6f45c'},{id:'amber',name:'Amber',rarity:'Uncommon',solid:'#ffc858'},{id:'iceblue',name:'Ice Blue',rarity:'Uncommon',solid:'#b9efff'},{id:'rose',name:'Rose',rarity:'Uncommon',solid:'#ff94a8'},
{id:'electric',name:'Electric Blue',rarity:'Rare',solid:'#4d71ff',classes:'fx-pulse'},{id:'hotpink',name:'Hot Pink',rarity:'Rare',solid:'#ff4cb8',classes:'fx-pulse'},{id:'toxic',name:'Toxic',rarity:'Rare',classes:'text-gradient fx-toxic'},{id:'ice',name:'Frozen',rarity:'Rare',classes:'text-gradient fx-ice'},
{id:'sunset',name:'Sunset',rarity:'Epic',gradient:'linear-gradient(100deg,#ff7a68,#ffb95c,#ff69ba,#8d6fff)',classes:'text-gradient fx-shift'},{id:'ocean',name:'Deep Ocean',rarity:'Epic',gradient:'linear-gradient(95deg,#7cf7ff,#2b90ff,#3145c8,#66eaff)',classes:'text-gradient fx-shift'},{id:'chrome',name:'Chrome',rarity:'Epic',classes:'text-gradient fx-chrome fx-shift'},
{id:'gold',name:'24K Gold',rarity:'Legendary',classes:'text-gradient fx-gold fx-shift'},{id:'magma',name:'Magma',rarity:'Legendary',classes:'text-gradient fx-magma fx-shift'},{id:'aurora',name:'Aurora',rarity:'Legendary',classes:'text-gradient fx-aurora fx-shift'},{id:'iridescent',name:'Iridescent',rarity:'Legendary',gradient:'linear-gradient(110deg,#6ff3ff,#c680ff,#ff8cc8,#fff08a,#77f4ff)',classes:'text-gradient fx-shift'},
{id:'void',name:'Void',rarity:'Mythic',classes:'text-gradient fx-void fx-shift'},{id:'blacklight',name:'Blacklight',rarity:'Mythic',classes:'text-gradient fx-blacklight fx-shift'},{id:'hologram',name:'Hologram',rarity:'Mythic',gradient:'linear-gradient(100deg,#fff,#6ff0ff,#be79ff,#ff86c8,#fff4a8,#fff)',classes:'text-gradient fx-shift'},
{id:'rainbow',name:'Prismatic',rarity:'Secret',classes:'text-gradient fx-rainbowbg fx-fast'},{id:'starlight',name:'Starlight',rarity:'Secret',classes:'text-gradient fx-starlight fx-shift'},{id:'spectrum',name:'Spectrum Shift',rarity:'Secret',gradient:'linear-gradient(90deg,#ff4d6d,#ffcf59,#65ff88,#5ee9ff,#706dff,#d86cff,#ff4d6d)',classes:'text-gradient fx-rainbow'}
].map(x=>({...x,type:'color',weight:.78+(hash(x.name)%51)/100}));
const fonts=[
{id:'space',name:'Space Grotesk',family:'Space Grotesk',rarity:'Common'},{id:'raj',name:'Rajdhani',family:'Rajdhani',rarity:'Common'},{id:'exo',name:'Exo 2',family:'Exo 2',rarity:'Common'},{id:'chakra',name:'Chakra Petch',family:'Chakra Petch',rarity:'Common'},{id:'teko',name:'Teko',family:'Teko',rarity:'Common'},
{id:'bebas',name:'Bebas Neue',family:'Bebas Neue',rarity:'Uncommon'},{id:'oxanium',name:'Oxanium',family:'Oxanium',rarity:'Uncommon'},{id:'syne',name:'Syne',family:'Syne',rarity:'Uncommon'},{id:'anton',name:'Anton',family:'Anton',rarity:'Uncommon'},{id:'russo',name:'Russo One',family:'Russo One',rarity:'Uncommon'},
{id:'righteous',name:'Righteous',family:'Righteous',rarity:'Rare'},{id:'cinzel',name:'Cinzel',family:'Cinzel',rarity:'Rare'},{id:'orbitron',name:'Orbitron',family:'Orbitron',rarity:'Rare'},{id:'audiowide',name:'Audiowide',family:'Audiowide',rarity:'Rare'},
{id:'blackops',name:'Black Ops One',family:'Black Ops One',rarity:'Epic'},{id:'bungee',name:'Bungee',family:'Bungee',rarity:'Epic'},{id:'unbounded',name:'Unbounded',family:'Unbounded',rarity:'Epic'},{id:'marker',name:'Permanent Marker',family:'Permanent Marker',rarity:'Epic'},
{id:'michroma',name:'Michroma',family:'Michroma',rarity:'Legendary'},{id:'press',name:'Press Start 2P',family:'Press Start 2P',rarity:'Legendary'},
{id:'monoton',name:'Monoton',family:'Monoton',rarity:'Mythic'},{id:'ultraorbit',name:'Orbitron Black',family:'Orbitron',rarity:'Mythic',style:'font-weight:900;letter-spacing:.11em'},{id:'royalcinzel',name:'Cinzel Black',family:'Cinzel',rarity:'Mythic',style:'font-weight:900;letter-spacing:.06em'},
{id:'voidtype',name:'Void Type',family:'Unbounded',rarity:'Secret',style:'font-weight:800;letter-spacing:.16em;font-style:italic'},{id:'arcade',name:'Arcade Core',family:'Press Start 2P',rarity:'Secret',style:'letter-spacing:.08em;text-transform:uppercase'}
].map(x=>({...x,type:'font',weight:.78+(hash(x.name)%51)/100}));
const pools={title:titles,color:colors,font:fonts};
function exactChance(item){const same=pools[item.type].filter(x=>x.rarity===item.rarity),sum=same.reduce((a,b)=>a+b.weight,0);return SHARES[item.type][item.rarity]/100*(item.weight/sum)}
function chanceText(item){const p=exactChance(item)*100;return p>=1?p.toFixed(2)+'%':p>=.1?p.toFixed(3)+'%':p.toFixed(4)+'%'}
function oneIn(item){const c=exactChance(item);return c?Math.round(1/c):0}
function pickRarity(type){let r=Math.random()*100,a=0;for(const rar of RARITY_ORDER){a+=SHARES[type][rar]||0;if(r<=a)return rar}return'Common'}
function weightedPick(arr){const total=arr.reduce((a,b)=>a+b.weight,0);let r=Math.random()*total;for(const x of arr){r-=x.weight;if(r<=0)return x}return arr.at(-1)}
function rollItem(type){const rarity=pickRarity(type);return weightedPick(pools[type].filter(x=>x.rarity===rarity))}
const playerId=titles.find(x=>x.name==='Player').id;
const defaults={inventory:{title:{[playerId]:1},color:{white:1},font:{space:1}},equipped:{title:playerId,color:'white',font:'space'},rolls:0,history:[]};
let save;try{save=JSON.parse(localStorage.getItem(STORAGE)||'null')||structuredClone(defaults)}catch{save=structuredClone(defaults)}
for(const t of ['title','color','font'])save.inventory[t] ||= {};save.equipped ||= structuredClone(defaults.equipped);save.history ||= [];save.rolls ||=0;
const persist=()=>localStorage.setItem(STORAGE,JSON.stringify(save));
let currentCase='title',rolling=false,autoRunning=false,invFilter='all';
const byId=(type,id)=>pools[type].find(x=>x.id===id), rarityColor=r=>RARITY[r]?.c||'#fff', typeLabel=t=>t==='title'?'TITLE':t==='color'?'COLOR':'FONT';
function clearFx(el){[...el.classList].filter(x=>x.startsWith('fx-')||x==='text-gradient').forEach(x=>el.classList.remove(x));for(const p of ['color','backgroundImage','fontFamily','fontWeight','letterSpacing','fontStyle','textTransform','filter'])el.style[p]=''}
function applyTextVisual(el,{text,color,font}){clearFx(el);el.textContent=text||'';if(color){if(color.classes)color.classes.split(' ').forEach(c=>el.classList.add(c));if(color.solid)el.style.color=color.solid;if(color.gradient){el.style.backgroundImage=color.gradient;el.classList.add('text-gradient')}}if(font){el.style.fontFamily=`"${font.family}",sans-serif`;if(font.style)font.style.split(';').filter(Boolean).forEach(rule=>{const i=rule.indexOf(':');if(i>0)el.style.setProperty(rule.slice(0,i).trim(),rule.slice(i+1).trim())})}}
function applyItemVisual(el,item){if(item.type==='color')applyTextVisual(el,{text:item.name,color:item});else if(item.type==='font')applyTextVisual(el,{text:item.name,font:item});else applyTextVisual(el,{text:item.name})}
function previewClass(item){return item.type==='color'?(item.classes||''):''}
function previewStyle(item){if(item.type==='font')return`font-family:"${item.family}",sans-serif;${item.style||''}`;if(item.type==='color'){if(item.solid)return`color:${item.solid}`;if(item.gradient)return`background-image:${item.gradient}`}return''}
const itemPreview=item=>item.name;
function updateEquipped(){const t=byId('title',save.equipped.title)||byId('title',playerId),c=byId('color',save.equipped.color)||colors[0],f=byId('font',save.equipped.font)||fonts[0];applyTextVisual($('#equippedTitle'),{text:t.name,color:c,font:f});$('#eqTitleName').textContent=t.name;$('#eqColorName').textContent=c.name.toUpperCase();$('#eqFontName').textContent=f.name.toUpperCase()}
function updateStats(){const owned=t=>Object.keys(save.inventory[t]).length,uniq=['title','color','font'].reduce((n,t)=>n+owned(t),0);$('#rollCount').textContent=save.rolls.toLocaleString();$('#uniqueCount').textContent=uniq;$('#invCount').textContent=uniq;$('#colTitles').textContent=`${owned('title')} / ${titles.length}`;$('#colColors').textContent=`${owned('color')} / ${colors.length}`;$('#colFonts').textContent=`${owned('font')} / ${fonts.length}`;$('#barTitles').style.width=owned('title')/titles.length*100+'%';$('#barColors').style.width=owned('color')/colors.length*100+'%';$('#barFonts').style.width=owned('font')/fonts.length*100+'%'}
function setView(view){$$('.view').forEach(x=>x.classList.remove('active'));$('#'+view+'View').classList.add('active');$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===view));if(view==='inventory')renderInventory();if(view==='collection')renderCollection()}
$$('.tab').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
$$('.load-chip').forEach(b=>b.addEventListener('click',()=>{setView('inventory');invFilter=b.dataset.go;$$('#invTabs button').forEach(x=>x.classList.toggle('active',x.dataset.filter===invFilter));renderInventory()}));
function selectCase(type){currentCase=type;$$('.case-card').forEach(x=>x.classList.toggle('selected',x.dataset.case===type));$('#machineEyebrow').textContent=typeLabel(type)+' CASE';$('#machineTitle').textContent='ROLL A '+typeLabel(type);buildIdleReel();renderOdds()}
$$('.case-card').forEach(b=>b.addEventListener('click',()=>selectCase(b.dataset.case)));
function reelRow(item,center=false){const d=document.createElement('div');d.className='reel-item'+(center?' centerish':'');d.innerHTML=`<span class="rarity" style="color:${rarityColor(item.rarity)}">${item.rarity.toUpperCase()}</span><span class="name ${previewClass(item)}" style="${previewStyle(item)}">${itemPreview(item)}</span><span class="chance">${chanceText(item)}</span>`;return d}
function buildIdleReel(){const track=$('#reelTrack');track.innerHTML='';Array.from({length:7},()=>rollItem(currentCase)).forEach((x,i)=>track.appendChild(reelRow(x,i===3)));track.style.transition='none';track.style.transform='translateY(-266px)';$('#resultRarity').textContent='READY';$('#resultRarity').style.color='#6e788d';clearFx($('#resultName'));$('#resultName').textContent='Press roll to start';$('#resultOdds').textContent='—'}
function addDrop(item){save.inventory[item.type][item.id]=(save.inventory[item.type][item.id]||0)+1;save.rolls++;save.history.unshift({type:item.type,id:item.id,ts:Date.now()});save.history=save.history.slice(0,18);persist();updateStats();renderHistory()}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),1600)}
async function performRoll({quick=false}={}){if(rolling)return null;rolling=true;$('#rollBtn').disabled=true;$('#autoBtn').disabled=true;const final=rollItem(currentCase),track=$('#reelTrack');track.innerHTML='';const count=quick?12:28,arr=Array.from({length:count-1},()=>rollItem(currentCase));arr.push(final);arr.forEach(x=>track.appendChild(reelRow(x)));track.style.transition='none';track.style.transform='translateY(0)';await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));track.style.transition=`transform ${quick?.78:2.35}s cubic-bezier(.08,.72,.12,1)`;track.style.transform=`translateY(${-((count-1)*76)-38}px)`;await new Promise(r=>setTimeout(r,quick?800:2380));[...track.children].forEach(x=>x.classList.remove('centerish'));track.lastElementChild?.classList.add('centerish');addDrop(final);$('#resultRarity').textContent=final.rarity.toUpperCase();$('#resultRarity').style.color=rarityColor(final.rarity);applyItemVisual($('#resultName'),final);$('#resultOdds').textContent=chanceText(final)+' · 1/'+oneIn(final);const strip=$('#resultStrip');strip.style.borderColor=rarityColor(final.rarity)+'66';setTimeout(()=>strip.style.borderColor='',800);rolling=false;if(!autoRunning){$('#rollBtn').disabled=false;$('#autoBtn').disabled=false}return final}
$('#rollBtn').addEventListener('click',()=>performRoll());
$('#autoBtn').addEventListener('click',async()=>{if(rolling||autoRunning)return;autoRunning=true;$('#rollBtn').disabled=true;$('#autoBtn').disabled=true;$('#autoBtn span').textContent='ROLLING…';for(let i=0;i<10;i++){await performRoll({quick:true});await new Promise(r=>setTimeout(r,110))}autoRunning=false;$('#rollBtn').disabled=false;$('#autoBtn').disabled=false;$('#autoBtn span').textContent='AUTO ×10';toast('Auto roll complete')});
function renderHistory(){const box=$('#historyList');box.innerHTML='';if(!save.history.length){box.innerHTML='<div class="empty-mini">No rolls yet.</div>';return}save.history.slice(0,6).forEach(h=>{const item=byId(h.type,h.id);if(!item)return;const d=document.createElement('div');d.className='history-item';d.innerHTML=`<small style="color:${rarityColor(item.rarity)}">${item.rarity.toUpperCase()} · ${typeLabel(item.type)}</small><b class="history-name"></b><em>${chanceText(item)}</em>`;applyItemVisual(d.querySelector('.history-name'),item);box.appendChild(d)})}
$('#clearHistory').addEventListener('click',()=>{save.history=[];persist();renderHistory()});
function equip(item){save.equipped[item.type]=item.id;persist();updateEquipped();renderInventory();toast(item.name+' equipped')}
function makeCard(item,{owned=false,qty=0,inventory=false}={}){const card=document.createElement('div');card.className=(inventory?'inv-card':'col-card')+(inventory?'':owned?' owned':' locked');card.style.setProperty('--soft',RARITY[item.rarity].soft);card.innerHTML=`<div class="item-top"><span class="item-type">${typeLabel(item.type)}</span><span class="item-rarity" style="color:${rarityColor(item.rarity)}">${item.rarity.toUpperCase()}</span></div><div class="item-preview ${previewClass(item)}" style="${previewStyle(item)}">${itemPreview(item)}</div><div class="item-name">${item.name}</div><div class="item-sub">${chanceText(item)} · ~1 in ${oneIn(item).toLocaleString()}</div>${inventory?`<div class="item-actions"><button class="equip-btn ${save.equipped[item.type]===item.id?'equipped':''}">${save.equipped[item.type]===item.id?'EQUIPPED':'EQUIP'}</button><span class="qty">×${qty}</span></div>`:'<span class="owned-dot"></span>'}`;if(inventory)card.querySelector('button').addEventListener('click',()=>equip(item));return card}
function renderInventory(){const grid=$('#inventoryGrid'),q=$('#invSearch').value.trim().toLowerCase();grid.innerHTML='';let list=[];for(const type of ['title','color','font'])for(const[id,qty]of Object.entries(save.inventory[type])){const item=byId(type,id);if(item)list.push({...item,qty})}list=list.filter(x=>(invFilter==='all'||x.type===invFilter)&&(!q||x.name.toLowerCase().includes(q))).sort((a,b)=>RARITY_ORDER.indexOf(b.rarity)-RARITY_ORDER.indexOf(a.rarity)||a.name.localeCompare(b.name));if(!list.length){grid.innerHTML='<div class="empty-mini">Nothing here yet. Roll some cases first.</div>';return}list.forEach(item=>grid.appendChild(makeCard(item,{owned:true,qty:item.qty,inventory:true})))}
$$('#invTabs button').forEach(b=>b.addEventListener('click',()=>{invFilter=b.dataset.filter;$$('#invTabs button').forEach(x=>x.classList.toggle('active',x===b));renderInventory()}));$('#invSearch').addEventListener('input',renderInventory);
function renderCollection(){const type=$('#collectionType').value,rar=$('#collectionRarity').value,q=$('#collectionSearch').value.trim().toLowerCase(),grid=$('#collectionGrid');grid.innerHTML='';let list=type==='all'?[...titles,...colors,...fonts]:[...pools[type]];list=list.filter(x=>(rar==='all'||x.rarity===rar)&&(!q||x.name.toLowerCase().includes(q)));const order=['title','color','font'];list.sort((a,b)=>{if(type==='all')return order.indexOf(a.type)-order.indexOf(b.type)||RARITY_ORDER.indexOf(a.rarity)-RARITY_ORDER.indexOf(b.rarity)||a.name.localeCompare(b.name);return RARITY_ORDER.indexOf(a.rarity)-RARITY_ORDER.indexOf(b.rarity)||b.weight-a.weight});list.forEach(item=>grid.appendChild(makeCard(item,{owned:!!save.inventory[item.type][item.id]})))}
$('#collectionType').addEventListener('change',renderCollection);$('#collectionRarity').addEventListener('change',renderCollection);$('#collectionSearch').addEventListener('input',renderCollection);
function renderOdds(){const type=currentCase,box=$('#oddsRarities');$('#oddsTitle').textContent=typeLabel(type)+' CASE ODDS';box.innerHTML='';RARITY_ORDER.forEach(r=>{const d=document.createElement('div');d.className='odds-row';d.innerHTML=`<span style="color:${rarityColor(r)}">${r.toUpperCase()}</span><b>${SHARES[type][r]}%</b>`;box.appendChild(d)})}
$('#oddsBtn').addEventListener('click',()=>{renderOdds();$('#oddsDialog').showModal()});$('#closeOdds').addEventListener('click',()=>$('#oddsDialog').close());$('#oddsDialog').addEventListener('click',e=>{if(e.target===$('#oddsDialog'))$('#oddsDialog').close()});
function initLegend(){const l=$('#rarityLegend');RARITY_ORDER.forEach(r=>{const x=document.createElement('span');x.className='rarity-pill';x.innerHTML=`<b style="color:${rarityColor(r)}">●</b>${r}`;l.appendChild(x)});const sel=$('#collectionRarity');RARITY_ORDER.forEach(r=>{const o=document.createElement('option');o.value=r;o.textContent=r;sel.appendChild(o)})}
function particles(){const cv=$('#particles'),ctx=cv.getContext('2d');let W,H,D,pts=[];function resize(){D=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;cv.width=W*D;cv.height=H*D;ctx.setTransform(D,0,0,D,0,0);pts=Array.from({length:Math.min(80,Math.floor(W*H/17000))},()=>({x:Math.random()*W,y:Math.random()*H,r:Math.random()*1.2+.25,v:Math.random()*.12+.025,a:Math.random()*.35+.07}))}function frame(){ctx.clearRect(0,0,W,H);for(const p of pts){p.y-=p.v;if(p.y<-4){p.y=H+4;p.x=Math.random()*W}ctx.globalAlpha=p.a;ctx.fillStyle='#bfefff';ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}requestAnimationFrame(frame)}addEventListener('resize',resize);resize();frame()}
$('#titlePoolCount').textContent=titles.length;$('#colorPoolCount').textContent=colors.length;$('#fontPoolCount').textContent=fonts.length;
const ct=$('#collectionType');if(ct){ct.querySelector('option[value="title"]')?.append(` (${titles.length})`);ct.querySelector('option[value="color"]')?.append(` (${colors.length})`);ct.querySelector('option[value="font"]')?.append(` (${fonts.length})`)}
initLegend();buildIdleReel();updateEquipped();updateStats();renderHistory();particles();renderOdds();
})();
