(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const STORAGE='roll_titles_v1';
const COST=250, INCOME=300, INCOME_MS=60000, STARTING_COINS=1000;
const DUP_REWARD={Common:50,Uncommon:80,Rare:125,Epic:225,Legendary:400,Mythic:750,Secret:1500};
const RARITY_ORDER=['Common','Uncommon','Rare','Epic','Legendary','Mythic','Secret'];
const RARITY={Common:{c:'#aeb7c4',soft:'rgba(174,183,196,.12)'},Uncommon:{c:'#62d894',soft:'rgba(98,216,148,.12)'},Rare:{c:'#58a9ff',soft:'rgba(88,169,255,.13)'},Epic:{c:'#aa72ff',soft:'rgba(170,114,255,.14)'},Legendary:{c:'#ffb34e',soft:'rgba(255,179,78,.14)'},Mythic:{c:'#ff5c9e',soft:'rgba(255,92,158,.14)'},Secret:{c:'#effdff',soft:'rgba(160,245,255,.18)'}};
const SHARES={title:{Common:45,Uncommon:25,Rare:14,Epic:8,Legendary:4.5,Mythic:2.5,Secret:1},color:{Common:48,Uncommon:25,Rare:13,Epic:7,Legendary:4,Mythic:2,Secret:1},font:{Common:40,Uncommon:25,Rare:15,Epic:9,Legendary:6,Mythic:3.5,Secret:1.5}};
const TITLE_NAMES={
Common:['Rookie','Player','Wanderer','Scout','Runner','Chill','Regular','New Face','Day One','Night Owl','Quick Hands','Low Key','No Rush','Solo Queue','Casual','Warmup','On Time','Good Luck','Just Here','The Backup','Side Quest','Locked In','Coffee Break','AFK-ish','Late Join','Fresh Start','One More','Main Menu','Safe Pick','Clean Slate','No Pressure','Easy Mode','Small Win','First Try','Next Up','Silent Type','The Usual','Plain Sight','Half Awake','Checkpoint','Good Enough','Lucky One','The Local','Second Wind','Steady','No Drama','Passing By','Starter Pack','Just Vibing','On Standby'],
Uncommon:['Hot Streak','Lone Wolf','No Signal','Clutch-ish','Fast Learner','Cold Hands','Good Timing','Night Shift','Early Access','Second Chance','One Tap','Full Focus','No Context','Clean Run','Side Character','Plot Armor','Unbothered','Peak Hours','Quiet Storm','Wild Card','Lucky Break','Close Call','Final Form?','Top Shelf','High Ground','No Sleep','After Hours','Main Character','Quick Reset','Zero Panic','Ghosted','Last Online','Low Battery','Rare Sight','Fresh Spawn','Off Script','Good Aim','Fast Lane','Sharp Mind','Late Night','Hidden Gem'],
Rare:['Apex Hunter','Neon Ghost','Final Round','Out of Bounds','Zero Hour','Silent Winner','Blue Flame','Dead Center','No Witness','Overclocked','Cold Blooded','Midnight Run','Perfect Timing','Unseen','Top Frag','Afterimage','Redline','Last Call','Hard Reset','Untouchable','No Recoil','Ghost Signal','Prime Time','Dark Horse','Ace Up','Skyline','Critical Hit','One Percent','Night Rider','Endgame','No Footsteps','Crosshair King','Half Past Midnight','Static Rush','Final Push'],
Epic:['Void Walker','Neon Phantom','Reality Check','Final Boss','Unchained','Blackout','Phase Shift','Dead Serious','Limit Break','Perfect Chaos','No Mercy','Lost Frequency','After Midnight','Cold Eclipse','Zero Gravity','Unreal','Last Light','Broken Halo','Static Heart','Purple Haze','Unwritten','False Prophet','Ghost Protocol','Overdrive','Neon Saint','Dead Channel','Glass Cannon','Phantom Mode'],
Legendary:['THE CHOSEN ONE','LAST SURVIVOR','KING OF NOTHING','FINAL WARNING','BORN LUCKY','NO SECOND PLACE','THE UNTOUCHABLE','END OF LINE','LIVING LEGEND','LAST ONE STANDING','CROWNLESS KING','THE ORIGINAL','PERFECT STORM','ONE ABOVE ALL','FINAL ANSWER','NO TURNING BACK','ETERNAL WINNER','THE MAIN EVENT','LAST WORD','NO CONTEST'],
Mythic:['REALITY BREAKER','BEYOND LIMITS','THE UNFORGOTTEN','NOT FROM HERE','WORLD ENDER','TIMELESS','VOIDBORN','THE IMPOSSIBLE','ABSOLUTE ZERO','FATE DENIED','ETERNAL ECHO','THE ANOMALY','UNKNOWN ENTITY','OUTSIDE REALITY'],
Secret:['NULL','404 : NOT FOUND','BEYOND','UNDEFINED','[ REDACTED ]','GODMODE','???','THE LAST TITLE','DO NOT ROLL','∞']};
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
const titles=[];Object.entries(TITLE_NAMES).forEach(([rarity,names])=>names.forEach(name=>titles.push({id:'t_'+hash(name).toString(36),type:'title',name,rarity,weight:.72+(hash(name)%57)/100})));
const colors=[
{id:'white',name:'White',rarity:'Common',solid:'#f4f7fb'},{id:'silver',name:'Silver',rarity:'Common',solid:'#b8c0cc'},{id:'slate',name:'Slate',rarity:'Common',solid:'#7f8a9d'},{id:'charcoal',name:'Charcoal',rarity:'Common',solid:'#555d6b'},{id:'red',name:'Red',rarity:'Common',solid:'#ff5d67'},{id:'blue',name:'Blue',rarity:'Common',solid:'#5d9dff'},{id:'green',name:'Green',rarity:'Common',solid:'#61d98c'},{id:'orange',name:'Orange',rarity:'Common',solid:'#ff9b54'},{id:'yellow',name:'Yellow',rarity:'Common',solid:'#ffe16b'},{id:'brown',name:'Brown',rarity:'Common',solid:'#b58968'},{id:'navy',name:'Navy',rarity:'Common',solid:'#6680b5'},{id:'teal',name:'Teal',rarity:'Common',solid:'#4db6a7'},
{id:'purple',name:'Purple',rarity:'Uncommon',solid:'#a375ff'},{id:'pink',name:'Pink',rarity:'Uncommon',solid:'#ff6fab'},{id:'cyan',name:'Cyan',rarity:'Uncommon',solid:'#66edff'},{id:'lime',name:'Lime',rarity:'Uncommon',solid:'#c6f45c'},{id:'amber',name:'Amber',rarity:'Uncommon',solid:'#ffc858'},{id:'iceblue',name:'Ice Blue',rarity:'Uncommon',solid:'#b9efff'},{id:'rose',name:'Rose',rarity:'Uncommon',solid:'#ff94a8'},{id:'mint',name:'Mint',rarity:'Uncommon',solid:'#86f4c3'},{id:'lavender',name:'Lavender',rarity:'Uncommon',solid:'#c6a8ff'},{id:'coral',name:'Coral',rarity:'Uncommon',solid:'#ff8e7e'},{id:'aqua',name:'Aqua',rarity:'Uncommon',solid:'#63ffe2'},{id:'crimson',name:'Crimson',rarity:'Uncommon',solid:'#e9435f'},
{id:'electric',name:'Electric Blue',rarity:'Rare',solid:'#4d71ff',classes:'fx-pulse'},{id:'hotpink',name:'Hot Pink',rarity:'Rare',solid:'#ff4cb8',classes:'fx-pulse'},{id:'toxic',name:'Toxic',rarity:'Rare',classes:'text-gradient fx-toxic'},{id:'ice',name:'Frozen',rarity:'Rare',classes:'text-gradient fx-ice'},{id:'neonred',name:'Neon Red',rarity:'Rare',solid:'#ff4b5d',classes:'fx-neonred'},{id:'neongreen',name:'Neon Green',rarity:'Rare',solid:'#62ff8b',classes:'fx-neongreen'},{id:'plasmaviolet',name:'Plasma Violet',rarity:'Rare',solid:'#b46cff',classes:'fx-plasmaviolet'},{id:'lasercyan',name:'Laser Cyan',rarity:'Rare',solid:'#54f5ff',classes:'fx-lasercyan'},{id:'acidyellow',name:'Acid Yellow',rarity:'Rare',solid:'#eaff45',classes:'fx-pulse'},{id:'deepteal',name:'Deep Teal',rarity:'Rare',solid:'#22d8c0',classes:'fx-pulse'},
{id:'sunset',name:'Sunset',rarity:'Epic',gradient:'linear-gradient(100deg,#ff7a68,#ffb95c,#ff69ba,#8d6fff)',classes:'text-gradient fx-shift'},{id:'ocean',name:'Deep Ocean',rarity:'Epic',gradient:'linear-gradient(95deg,#7cf7ff,#2b90ff,#3145c8,#66eaff)',classes:'text-gradient fx-shift'},{id:'chrome',name:'Chrome',rarity:'Epic',classes:'text-gradient fx-chrome fx-shift'},{id:'cotton',name:'Cotton Candy',rarity:'Epic',classes:'text-gradient fx-cotton fx-shift'},{id:'forest',name:'Forest Mist',rarity:'Epic',classes:'text-gradient fx-forest fx-shift'},{id:'cosmic',name:'Cosmic Dust',rarity:'Epic',classes:'text-gradient fx-cosmic fx-shift'},{id:'vapor',name:'Vaporwave',rarity:'Epic',classes:'text-gradient fx-vapor fx-shift'},{id:'bloodmoon',name:'Blood Moon',rarity:'Epic',classes:'text-gradient fx-bloodmoon fx-shift'},{id:'rosegold',name:'Rose Gold',rarity:'Epic',gradient:'linear-gradient(100deg,#8e5d5f,#ffd1c8,#d18a8e,#fff0e6,#9f6567)',classes:'text-gradient fx-shift'},
{id:'gold',name:'24K Gold',rarity:'Legendary',classes:'text-gradient fx-gold fx-shift'},{id:'magma',name:'Magma',rarity:'Legendary',classes:'text-gradient fx-magma fx-shift'},{id:'aurora',name:'Aurora',rarity:'Legendary',classes:'text-gradient fx-aurora fx-shift'},{id:'iridescent',name:'Iridescent',rarity:'Legendary',gradient:'linear-gradient(110deg,#6ff3ff,#c680ff,#ff8cc8,#fff08a,#77f4ff)',classes:'text-gradient fx-shift'},{id:'emerald',name:'Emerald Flame',rarity:'Legendary',classes:'text-gradient fx-emerald fx-shift'},{id:'solar',name:'Solar Flare',rarity:'Legendary',classes:'text-gradient fx-solar fx-shift'},{id:'amethyst',name:'Royal Amethyst',rarity:'Legendary',classes:'text-gradient fx-amethyst fx-shift'},{id:'cyber',name:'Cyberpunk',rarity:'Legendary',classes:'text-gradient fx-cyber fx-shift'},
{id:'void',name:'Void',rarity:'Mythic',classes:'text-gradient fx-void fx-shift'},{id:'blacklight',name:'Blacklight',rarity:'Mythic',classes:'text-gradient fx-blacklight fx-shift'},{id:'hologram',name:'Hologram',rarity:'Mythic',gradient:'linear-gradient(100deg,#fff,#6ff0ff,#be79ff,#ff86c8,#fff4a8,#fff)',classes:'text-gradient fx-shift'},{id:'nebula',name:'Nebula',rarity:'Mythic',classes:'text-gradient fx-nebula fx-shift'},{id:'singularity',name:'Singularity',rarity:'Mythic',classes:'text-gradient fx-singularity fx-shift'},{id:'angelic',name:'Angelic',rarity:'Mythic',classes:'text-gradient fx-angelic fx-shift'},{id:'inferno',name:'Inferno Core',rarity:'Mythic',classes:'text-gradient fx-inferno fx-shift'},
{id:'rainbow',name:'Prismatic',rarity:'Secret',classes:'text-gradient fx-rainbowbg fx-fast'},{id:'starlight',name:'Starlight',rarity:'Secret',classes:'text-gradient fx-starlight fx-shift'},{id:'spectrum',name:'Spectrum Shift',rarity:'Secret',gradient:'linear-gradient(90deg,#ff4d6d,#ffcf59,#65ff88,#5ee9ff,#706dff,#d86cff,#ff4d6d)',classes:'text-gradient fx-rainbow'},{id:'rgbover',name:'RGB Overdrive',rarity:'Secret',classes:'text-gradient fx-rgbover'},{id:'galaxy',name:'Galaxy',rarity:'Secret',classes:'text-gradient fx-galaxy fx-shift'},{id:'divine',name:'Divine',rarity:'Secret',classes:'text-gradient fx-divine fx-shift'},{id:'glitchmatrix',name:'Glitch Matrix',rarity:'Secret',classes:'text-gradient fx-glitchmatrix'}
].map(x=>({...x,type:'color',weight:.78+(hash(x.name)%51)/100}));
function F(id,name,family,rarity,style=''){return{id,type:'font',name,family,rarity,style,weight:.78+(hash(name)%51)/100}}
const fonts=[
F('space','Space Grotesk','Space Grotesk','Common'),F('raj','Rajdhani','Rajdhani','Common'),F('exo','Exo 2','Exo 2','Common'),F('chakra','Chakra Petch','Chakra Petch','Common'),F('teko','Teko','Teko','Common'),F('kanit','Kanit','Kanit','Common'),F('jura','Jura','Jura','Common'),F('quantico','Quantico','Quantico','Common'),F('tomorrow','Tomorrow','Tomorrow','Common'),F('arial','Arial','Arial','Common'),
F('bebas','Bebas Neue','Bebas Neue','Uncommon'),F('oxanium','Oxanium','Oxanium','Uncommon'),F('syne','Syne','Syne','Uncommon'),F('anton','Anton','Anton','Uncommon'),F('russo','Russo One','Russo One','Uncommon'),F('fredoka','Fredoka','Fredoka','Uncommon'),F('graduate','Graduate','Graduate','Uncommon'),F('iceberg','Iceberg','Iceberg','Uncommon'),F('sharetech','Share Tech Mono','Share Tech Mono','Uncommon'),F('poiret','Poiret One','Poiret One','Uncommon'),
F('righteous','Righteous','Righteous','Rare'),F('cinzel','Cinzel','Cinzel','Rare'),F('orbitron','Orbitron','Orbitron','Rare'),F('audiowide','Audiowide','Audiowide','Rare'),F('bangers','Bangers','Bangers','Rare'),F('archivo','Archivo Black','Archivo Black','Rare'),F('syncopate','Syncopate','Syncopate','Rare'),F('specialelite','Special Elite','Special Elite','Rare'),F('georgia','Georgia','Georgia','Rare','font-weight:700;letter-spacing:.03em'),
F('blackops','Black Ops One','Black Ops One','Epic'),F('bungee','Bungee','Bungee','Epic'),F('unbounded','Unbounded','Unbounded','Epic'),F('marker','Permanent Marker','Permanent Marker','Epic'),F('alfaslab','Alfa Slab One','Alfa Slab One','Epic'),F('rubikmono','Rubik Mono One','Rubik Mono One','Epic'),F('wallpoet','Wallpoet','Wallpoet','Epic'),F('metalmania','Metal Mania','Metal Mania','Epic'),F('notableepic','Notable','Notable','Epic'),
F('michroma','Michroma','Michroma','Legendary'),F('press','Press Start 2P','Press Start 2P','Legendary'),F('krona','Krona One','Krona One','Legendary'),F('limelight','Limelight','Limelight','Legendary'),F('majormono','Major Mono Display','Major Mono Display','Legendary'),F('bowlby','Bowlby One SC','Bowlby One SC','Legendary'),F('notable','Notable Heavy','Notable','Legendary','letter-spacing:.08em'),
F('monoton','Monoton','Monoton','Mythic'),F('ultraorbit','Orbitron Black','Orbitron','Mythic','font-weight:900;letter-spacing:.11em'),F('royalcinzel','Cinzel Black','Cinzel','Mythic','font-weight:900;letter-spacing:.06em'),F('creepster','Creepster','Creepster','Mythic','letter-spacing:.08em'),F('tiltneon','Tilt Neon','Tilt Neon','Mythic','letter-spacing:.06em'),F('monoblack','Mono Black','Major Mono Display','Mythic','font-weight:900;letter-spacing:.12em'),
F('voidtype','Void Type','Unbounded','Secret','font-weight:800;letter-spacing:.16em;font-style:italic'),F('arcade','Arcade Core','Press Start 2P','Secret','letter-spacing:.08em;text-transform:uppercase'),F('brokensignal','Broken Signal','Share Tech Mono','Secret','font-weight:700;letter-spacing:.22em;font-style:italic'),F('hyperwave','Hyperwave','Audiowide','Secret','font-weight:700;letter-spacing:.15em'),F('ritual','Ritual','Metal Mania','Secret','font-weight:700;letter-spacing:.12em')
];
const pools={title:titles,color:colors,font:fonts};
function exactChance(item){const same=pools[item.type].filter(x=>x.rarity===item.rarity),sum=same.reduce((a,b)=>a+b.weight,0);return SHARES[item.type][item.rarity]/100*(item.weight/sum)}
function chanceText(item){const p=exactChance(item)*100;return p>=1?p.toFixed(2)+'%':p>=.1?p.toFixed(3)+'%':p.toFixed(4)+'%'}
function oneIn(item){const c=exactChance(item);return c?Math.round(1/c):0}
function pickRarity(type){let r=Math.random()*100,a=0;for(const rar of RARITY_ORDER){a+=SHARES[type][rar]||0;if(r<=a)return rar}return'Common'}
function weightedPick(arr){const total=arr.reduce((a,b)=>a+b.weight,0);let r=Math.random()*total;for(const x of arr){r-=x.weight;if(r<=0)return x}return arr[arr.length-1]}
function rollItem(type){const rarity=pickRarity(type);return weightedPick(pools[type].filter(x=>x.rarity===rarity))}
const playerId=titles.find(x=>x.name==='Player').id;
const defaults={inventory:{title:{[playerId]:1},color:{white:1},font:{space:1}},equipped:{title:playerId,color:'white',font:'space'},rolls:0,history:[],coins:STARTING_COINS,lastIncomeAt:Date.now()};
let save;try{save=JSON.parse(localStorage.getItem(STORAGE)||'null')||structuredClone(defaults)}catch{save=structuredClone(defaults)}
for(const t of ['title','color','font'])save.inventory[t] ||= {};
save.equipped ||= structuredClone(defaults.equipped);save.history ||= [];save.rolls ||=0;
if(!Number.isFinite(save.coins))save.coins=STARTING_COINS;
if(!Number.isFinite(save.lastIncomeAt))save.lastIncomeAt=Date.now();
if(!pools.title.some(x=>x.id===save.equipped.title))save.equipped.title=playerId;
if(!pools.color.some(x=>x.id===save.equipped.color))save.equipped.color='white';
if(!pools.font.some(x=>x.id===save.equipped.font))save.equipped.font='space';
const persist=()=>localStorage.setItem(STORAGE,JSON.stringify(save));
let currentCase='title',rolling=false,autoRunning=false,invFilter='all';
const byId=(type,id)=>pools[type].find(x=>x.id===id), rarityColor=r=>RARITY[r]?.c||'#fff', typeLabel=t=>t==='title'?'TITLE':t==='color'?'COLOR':'FONT';
function clearFx(el){[...el.classList].filter(x=>x.startsWith('fx-')||x==='text-gradient').forEach(x=>el.classList.remove(x));for(const p of ['color','backgroundImage','fontFamily','fontWeight','letterSpacing','fontStyle','textTransform','filter'])el.style[p]=''}
function applyFontRules(el,font){if(!font)return;el.style.fontFamily=`"${font.family}",sans-serif`;if(font.style)font.style.split(';').filter(Boolean).forEach(rule=>{const i=rule.indexOf(':');if(i>0)el.style.setProperty(rule.slice(0,i).trim(),rule.slice(i+1).trim())})}
function applyTextVisual(el,{text,color,font}){clearFx(el);el.textContent=text||'';if(color){if(color.classes)color.classes.split(' ').forEach(c=>el.classList.add(c));if(color.solid)el.style.color=color.solid;if(color.gradient){el.style.backgroundImage=color.gradient;el.classList.add('text-gradient')}}applyFontRules(el,font)}
function applyItemVisual(el,item){if(item.type==='color')applyTextVisual(el,{text:item.name,color:item});else if(item.type==='font')applyTextVisual(el,{text:item.name,font:item});else applyTextVisual(el,{text:item.name})}
function previewClass(item){return item.type==='color'?(item.classes||''):''}
function previewStyle(item){if(item.type==='font')return`font-family:"${item.family}",sans-serif;${item.style||''}`;if(item.type==='color'){if(item.solid)return`color:${item.solid}`;if(item.gradient)return`background-image:${item.gradient}`}return''}
const itemPreview=item=>item.name;
function updateEquipped(){const t=byId('title',save.equipped.title)||byId('title',playerId),c=byId('color',save.equipped.color)||colors[0],f=byId('font',save.equipped.font)||fonts[0];applyTextVisual($('#equippedTitle'),{text:t.name,color:c,font:f});$('#eqTitleName').textContent=t.name;$('#eqColorName').textContent=c.name.toUpperCase();$('#eqFontName').textContent=f.name.toUpperCase();applyFontRules($('#eqFontName'),f)}
function ownedCount(type){return Object.keys(save.inventory[type]).filter(id=>!!byId(type,id)).length}
function updateStats(){const a=ownedCount('title'),b=ownedCount('color'),c=ownedCount('font'),uniq=a+b+c;$('#rollCount').textContent=save.rolls.toLocaleString();$('#uniqueCount').textContent=uniq;$('#invCount').textContent=uniq;$('#invAllCount').textContent=uniq;$('#invTitleCount').textContent=a;$('#invColorCount').textContent=b;$('#invFontCount').textContent=c;$('#colTitles').textContent=`${a} / ${titles.length}`;$('#colColors').textContent=`${b} / ${colors.length}`;$('#colFonts').textContent=`${c} / ${fonts.length}`;$('#barTitles').style.width=a/titles.length*100+'%';$('#barColors').style.width=b/colors.length*100+'%';$('#barFonts').style.width=c/fonts.length*100+'%'}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),1900)}
function syncButtons(){if(rolling||autoRunning){$('#rollBtn').disabled=true;$('#autoBtn').disabled=true;return}const ok=save.coins>=COST;$('#rollBtn').disabled=!ok;$('#autoBtn').disabled=!ok}
function updateWallet(){$('#coinBalance').textContent=Math.floor(save.coins).toLocaleString();const left=Math.max(0,Math.ceil((save.lastIncomeAt+INCOME_MS-Date.now())/1000));$('#incomeTimer').textContent=left+'s';syncButtons()}
function settleIncome(showToast=false){const now=Date.now();if(now<save.lastIncomeAt)save.lastIncomeAt=now;const mins=Math.floor((now-save.lastIncomeAt)/INCOME_MS);if(mins>0){const gain=mins*INCOME;save.coins+=gain;save.lastIncomeAt+=mins*INCOME_MS;persist();updateWallet();if(showToast)toast(`+${gain.toLocaleString()} coins · passive income`);return gain}updateWallet();return 0}
const startupIncome=settleIncome(false);setInterval(()=>settleIncome(true),1000);
function setView(view){$$('.view').forEach(x=>x.classList.remove('active'));$('#'+view+'View').classList.add('active');$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===view));if(view==='inventory')renderInventory();if(view==='collection')renderCollection()}
$$('.tab').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
$$('.load-chip').forEach(b=>b.addEventListener('click',()=>{setView('inventory');invFilter=b.dataset.go;$$('#invTabs button').forEach(x=>x.classList.toggle('active',x.dataset.filter===invFilter));renderInventory()}));
function selectCase(type){currentCase=type;$$('.case-card').forEach(x=>x.classList.toggle('selected',x.dataset.case===type));$('#machineEyebrow').textContent=typeLabel(type)+' CASE';$('#machineTitle').textContent='ROLL A '+typeLabel(type);buildIdleReel();renderOdds()}
$$('.case-card').forEach(b=>b.addEventListener('click',()=>selectCase(b.dataset.case)));
function reelRow(item,center=false){const d=document.createElement('div');d.className='reel-item'+(center?' centerish':'');d.innerHTML=`<span class="rarity" style="color:${rarityColor(item.rarity)}">${item.rarity.toUpperCase()}</span><span class="name ${previewClass(item)}" style="${previewStyle(item)}">${itemPreview(item)}</span><span class="chance">${chanceText(item)}</span>`;return d}
function buildIdleReel(){const track=$('#reelTrack');track.innerHTML='';Array.from({length:7},()=>rollItem(currentCase)).forEach((x,i)=>track.appendChild(reelRow(x,i===3)));track.style.transition='none';track.style.transform='translateY(-266px)';$('#resultRarity').textContent='READY';$('#resultRarity').style.color='#6e788d';clearFx($('#resultName'));$('#resultName').textContent='Press roll to start';$('#resultOdds').classList.remove('duplicate');$('#resultOdds').textContent='—'}
function addDrop(item){const before=save.inventory[item.type][item.id]||0,duplicate=before>0,refund=duplicate?DUP_REWARD[item.rarity]:0;save.inventory[item.type][item.id]=before+1;save.rolls++;if(refund)save.coins+=refund;save.history.unshift({type:item.type,id:item.id,ts:Date.now(),duplicate,refund});save.history=save.history.slice(0,24);persist();updateStats();updateWallet();renderHistory();return{duplicate,refund}}
async function performRoll({quick=false}={}){if(rolling)return null;settleIncome(false);if(save.coins<COST){toast(`Need ${COST.toLocaleString()} coins to roll`);syncButtons();return null}save.coins-=COST;persist();updateWallet();rolling=true;syncButtons();const final=rollItem(currentCase),track=$('#reelTrack');track.innerHTML='';const count=quick?12:28,arr=Array.from({length:count-1},()=>rollItem(currentCase));arr.push(final);arr.forEach(x=>track.appendChild(reelRow(x)));track.style.transition='none';track.style.transform='translateY(0)';await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));track.style.transition=`transform ${quick?.78:2.35}s cubic-bezier(.08,.72,.12,1)`;track.style.transform=`translateY(${-((count-1)*76)-38}px)`;await new Promise(r=>setTimeout(r,quick?800:2380));[...track.children].forEach(x=>x.classList.remove('centerish'));track.lastElementChild?.classList.add('centerish');const drop=addDrop(final);$('#resultRarity').textContent=final.rarity.toUpperCase();$('#resultRarity').style.color=rarityColor(final.rarity);applyItemVisual($('#resultName'),final);$('#resultOdds').classList.toggle('duplicate',drop.duplicate);$('#resultOdds').textContent=drop.duplicate?`DUPLICATE +${drop.refund.toLocaleString()} ◈`:`${chanceText(final)} · 1/${oneIn(final)}`;const strip=$('#resultStrip');strip.style.borderColor=rarityColor(final.rarity)+'66';setTimeout(()=>strip.style.borderColor='',800);rolling=false;if(!autoRunning)syncButtons();return final}
$('#rollBtn').addEventListener('click',()=>performRoll());
$('#autoBtn').addEventListener('click',async()=>{if(rolling||autoRunning)return;autoRunning=true;syncButtons();$('#autoBtn span').textContent='ROLLING…';let done=0;for(let i=0;i<10;i++){const item=await performRoll({quick:true});if(!item)break;done++;await new Promise(r=>setTimeout(r,100))}autoRunning=false;$('#autoBtn span').textContent='AUTO ×10';syncButtons();toast(done===10?'Auto ×10 complete':`Auto stopped after ${done} roll${done===1?'':'s'}`)});
function renderHistory(){const box=$('#historyList');box.innerHTML='';if(!save.history.length){box.innerHTML='<div class="empty-mini">No rolls yet.</div>';return}save.history.slice(0,6).forEach(h=>{const item=byId(h.type,h.id);if(!item)return;const d=document.createElement('div');d.className='history-item';d.innerHTML=`<small style="color:${rarityColor(item.rarity)}">${item.rarity.toUpperCase()} · ${typeLabel(item.type)}</small><b class="history-name"></b><em>${chanceText(item)}</em>${h.duplicate?`<span class="dup-refund">DUP +${Number(h.refund||0).toLocaleString()} ◈</span>`:''}`;applyItemVisual(d.querySelector('.history-name'),item);box.appendChild(d)})}
$('#clearHistory').addEventListener('click',()=>{save.history=[];persist();renderHistory()});
function equip(item){save.equipped[item.type]=item.id;persist();updateEquipped();renderInventory();toast(item.name+' equipped')}
function makeCard(item,{owned=false,qty=0,inventory=false}={}){const card=document.createElement('div');card.className=(inventory?'inv-card':'col-card')+(inventory?'':owned?' owned':' locked');card.style.setProperty('--soft',RARITY[item.rarity].soft);card.innerHTML=`<div class="item-top"><span class="item-type">${typeLabel(item.type)}</span><span class="item-rarity" style="color:${rarityColor(item.rarity)}">${item.rarity.toUpperCase()}</span></div><div class="item-preview"></div><div class="item-name"></div><div class="item-sub">${chanceText(item)} · ~1 in ${oneIn(item).toLocaleString()}</div>${inventory?`<div class="item-actions"><button class="equip-btn ${save.equipped[item.type]===item.id?'equipped':''}">${save.equipped[item.type]===item.id?'EQUIPPED':'EQUIP'}</button><span class="qty">×${qty}</span></div>`:'<span class="owned-dot"></span>'}`;const prev=card.querySelector('.item-preview'),name=card.querySelector('.item-name');applyItemVisual(prev,item);name.textContent=item.name;if(item.type==='font'){prev.classList.add('font-preview');name.classList.add('font-name');applyFontRules(name,item)}if(inventory)card.querySelector('button').addEventListener('click',()=>equip(item));return card}
function renderInventory(){const grid=$('#inventoryGrid'),q=$('#invSearch').value.trim().toLowerCase();grid.innerHTML='';let list=[];for(const type of ['title','color','font'])for(const[id,qty]of Object.entries(save.inventory[type])){const item=byId(type,id);if(item)list.push({...item,qty})}list=list.filter(x=>(invFilter==='all'||x.type===invFilter)&&(!q||x.name.toLowerCase().includes(q))).sort((a,b)=>RARITY_ORDER.indexOf(b.rarity)-RARITY_ORDER.indexOf(a.rarity)||a.name.localeCompare(b.name));if(!list.length){grid.innerHTML='<div class="empty-mini">Nothing here yet. Roll some cases first.</div>';return}list.forEach(item=>grid.appendChild(makeCard(item,{owned:true,qty:item.qty,inventory:true})))}
$$('#invTabs button').forEach(b=>b.addEventListener('click',()=>{invFilter=b.dataset.filter;$$('#invTabs button').forEach(x=>x.classList.toggle('active',x===b));renderInventory()}));$('#invSearch').addEventListener('input',renderInventory);
function renderCollection(){const type=$('#collectionType').value,rar=$('#collectionRarity').value,q=$('#collectionSearch').value.trim().toLowerCase(),grid=$('#collectionGrid');grid.innerHTML='';let list=type==='all'?[...titles,...colors,...fonts]:[...pools[type]];list=list.filter(x=>(rar==='all'||x.rarity===rar)&&(!q||x.name.toLowerCase().includes(q)));const order=['title','color','font'];list.sort((a,b)=>type==='all'?order.indexOf(a.type)-order.indexOf(b.type)||RARITY_ORDER.indexOf(a.rarity)-RARITY_ORDER.indexOf(b.rarity)||a.name.localeCompare(b.name):RARITY_ORDER.indexOf(a.rarity)-RARITY_ORDER.indexOf(b.rarity)||b.weight-a.weight);list.forEach(item=>grid.appendChild(makeCard(item,{owned:!!save.inventory[item.type][item.id]}))}
$('#collectionType').addEventListener('change',renderCollection);$('#collectionRarity').addEventListener('change',renderCollection);$('#collectionSearch').addEventListener('input',renderCollection);
function renderOdds(){const type=currentCase,box=$('#oddsRarities');$('#oddsTitle').textContent=typeLabel(type)+' CASE ODDS';box.innerHTML='';RARITY_ORDER.forEach(r=>{const d=document.createElement('div');d.className='odds-row';d.innerHTML=`<span style="color:${rarityColor(r)}">${r.toUpperCase()}</span><b>${SHARES[type][r]}%</b>`;box.appendChild(d)});const dup=$('#duplicateRewards');dup.innerHTML='';RARITY_ORDER.forEach(r=>{const d=document.createElement('div');d.className='duplicate-row';d.innerHTML=`<span style="color:${rarityColor(r)}">${r.toUpperCase()}</span><b>+${DUP_REWARD[r]} ◈</b>`;dup.appendChild(d)})}
$('#oddsBtn').addEventListener('click',()=>{renderOdds();$('#oddsDialog').showModal()});$('#closeOdds').addEventListener('click',()=>$('#oddsDialog').close());$('#oddsDialog').addEventListener('click',e=>{if(e.target===$('#oddsDialog'))$('#oddsDialog').close()});
function initLegend(){const l=$('#rarityLegend');RARITY_ORDER.forEach(r=>{const x=document.createElement('span');x.className='rarity-pill';x.innerHTML=`<b style="color:${rarityColor(r)}">●</b>${r}`;l.appendChild(x)});const sel=$('#collectionRarity');RARITY_ORDER.forEach(r=>{const o=document.createElement('option');o.value=r;o.textContent=r;sel.appendChild(o)})}
function populateAdminItems(){const type=$('#adminGrantType').value,amountWrap=$('#adminAmountWrap'),itemWrap=$('#adminItemWrap'),sel=$('#adminItem');amountWrap.classList.toggle('hidden',type!=='coins');itemWrap.classList.toggle('hidden',!['title','color','font'].includes(type));if(['title','color','font'].includes(type)){sel.innerHTML='';[...pools[type]].sort((a,b)=>RARITY_ORDER.indexOf(b.rarity)-RARITY_ORDER.indexOf(a.rarity)||a.name.localeCompare(b.name)).forEach(item=>{const o=document.createElement('option');o.value=item.id;o.textContent=`${item.rarity.toUpperCase()} — ${item.name}`;sel.appendChild(o)})}}
$('#adminOpen').addEventListener('click',()=>{$('#adminStatus').textContent='';populateAdminItems();$('#adminDialog').showModal()});$('#adminClose').addEventListener('click',()=>$('#adminDialog').close());$('#adminGrantType').addEventListener('change',populateAdminItems);$('#adminDialog').addEventListener('click',e=>{if(e.target===$('#adminDialog'))$('#adminDialog').close()});
$('#adminGrant').addEventListener('click',async()=>{const code=$('#adminCode').value,status=$('#adminStatus'),btn=$('#adminGrant');status.className='admin-status';status.textContent='Checking code…';btn.disabled=true;try{const res=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})});const data=await res.json().catch(()=>({}));if(!res.ok||!data.ok)throw new Error(data.error||'Admin verification failed');const type=$('#adminGrantType').value;if(type==='coins'){const amount=Math.floor(Number($('#adminAmount').value));if(!Number.isFinite(amount)||amount<1||amount>1e9)throw new Error('Choose an amount between 1 and 1,000,000,000');save.coins+=amount;status.textContent=`Granted ${amount.toLocaleString()} coins.`}else if(type==='all'){for(const t of ['title','color','font'])for(const item of pools[t])save.inventory[t][item.id]=Math.max(1,save.inventory[t][item.id]||0);status.textContent='Granted every title, color and font.'}else{const item=byId(type,$('#adminItem').value);if(!item)throw new Error('Item not found');save.inventory[type][item.id]=Math.max(1,save.inventory[type][item.id]||0);status.textContent=`Granted ${item.name}.`}persist();updateStats();updateWallet();updateEquipped();renderInventory();renderCollection();status.classList.add('good');toast('Admin grant applied')}catch(err){status.textContent=err.message;status.classList.add('bad')}finally{btn.disabled=false}});
function particles(){const cv=$('#particles'),ctx=cv.getContext('2d');let W,H,D,pts=[];function resize(){D=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;cv.width=W*D;cv.height=H*D;ctx.setTransform(D,0,0,D,0,0);pts=Array.from({length:Math.min(80,Math.floor(W*H/17000))},()=>({x:Math.random()*W,y:Math.random()*H,r:Math.random()*1.2+.25,v:Math.random()*.12+.025,a:Math.random()*.35+.07}))}function frame(){ctx.clearRect(0,0,W,H);for(const p of pts){p.y-=p.v;if(p.y<-4){p.y=H+4;p.x=Math.random()*W}ctx.globalAlpha=p.a;ctx.fillStyle='#bfefff';ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}requestAnimationFrame(frame)}addEventListener('resize',resize);resize();frame()}
$('#titlePoolCount').textContent=titles.length;$('#colorPoolCount').textContent=colors.length;$('#fontPoolCount').textContent=fonts.length;const ct=$('#collectionType');ct.querySelector('option[value="title"]').textContent=`Titles (${titles.length})`;ct.querySelector('option[value="color"]').textContent=`Colors (${colors.length})`;ct.querySelector('option[value="font"]').textContent=`Fonts (${fonts.length})`;
initLegend();buildIdleReel();updateEquipped();updateStats();updateWallet();renderHistory();renderOdds();particles();populateAdminItems();persist();if(startupIncome>0)setTimeout(()=>toast(`+${startupIncome.toLocaleString()} coins while you were away`),350);
})();
